#spring:
#  datasource:
#    url: ${DB_URL}
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            clientId: ${G_CLIENT_ID}
#            clientSecret: ${G_CLIENT_SECRET}
#            scope:
#              - email
#              - profile
#logging:
#  level:
#    org:
#      springframework:
#        orm:
#          jpa: DEBUG
#server:
#  servlet:
#    encoding:
#      force-response: true
#
#mail:
#  address:
#    admin: admin@admin.com # 환경변수로 바꿔줘야됨
#
#jwt:
#  key: ${JWT_SECRET_KEY}
#  access-token-expiration-minutes: 600
#  refresh-token-expiration-minutes: 420